require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.6
  ExtraDetails: true
  Exclude:
    - bin/*
    - vendor/**/*

Layout/CaseIndentation:
  IndentOneStep: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/LineLength:
  Max: 128

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Naming/BlockForwarding:
  EnforcedStyle: explicit

Naming/MethodParameterName:
  AllowedNames:
    - i
    - w
    - x
    - y
    - z
    - md
    - op

Naming/VariableNumber:
  AllowedPatterns:
    - '_9001\z'

RSpec/FilePath:
  Enabled: false

RSpec/SpecFilePathFormat:
  CustomTransform:
    AoC2024: aoc2024

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/CharacterLiteral:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/MixinUsage:
  Exclude:
    - spec/**/*

Style/ParallelAssignment:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes
